# This rule is not used by the project configmapsync itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the apps.kapendra.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: configmapsync
    app.kubernetes.io/managed-by: kustomize
  name: configmapsync-editor-role
rules:
- apiGroups:
  - apps.kapendra.com
  resources:
  - configmapsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kapendra.com
  resources:
  - configmapsyncs/status
  verbs:
  - get
